Feature/add logger template
snuailab/waffle_utils pull request #42
Opened 2023-03-16 07:10 UTC by ByteBrewer

## Changes Made
- Added base logger template
- Converted the `print()` to `logger.info()`

2023-03-16 23:43 UTC, ZeroAct requested changes

2023-03-16 23:43 UTC, ZeroAct commented on waffle_utils/log/config.py
Logger template may recieve parameters like `file_path`, `logging.LEVEL` under **OUR** default settings.

And usecase should be more simple.
like
```
# not simple enough
config.get_logger()
logger = logging.getLogger(__name__)

# simple and equivalent with build-in module
from waffle_utils.log import logging
logger = logging.getLogger(__name__)
```

2023-03-17 00:18 UTC, dustjr1565 approved these changes

2023-03-19 11:37 UTC, ByteBrewer commented on waffle_utils/log/config.py
@ZeroAct  To clarify, I want to hear the use case from you to check we are on the same page.

Here's the use case I guessed.
```python
from waffle_utils.log import logging
logger = logging.getLogger(__name__)

logger.set_logger_path("path/to/logs")

logger.info("This is waffle info logger")
logger.debug("This is waffle debug logger")
logger.warning("This is waffle warning logger")
```

Am I understanding right?

2023-03-20 06:24 UTC, dustjr1565 approved these changes

2023-03-20 06:24 UTC, ZeroAct approved these changes

2023-03-20 06:24 UTC, merged